services:
  - type: web
    name: agentic-finance
    env: python
    buildCommand: cd src/frontend/react-dashboard && npm install && npm run build && pip install -r requirements.txt
    startCommand: python run_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: RENDER
        value: "true" 